config/routes.rb
RenRenBook::Application.routes.draw do
<<<<<<< HEAD
  root :to=>'Renren#new'
  get "sessions/new"
=======

  resources :contacts

  resources :ownerships
>>>>>>> 9d8520a26919d100ddea3e527826d87986038c1d

  match "books/search/:q" => 'books#search'
  match "books/search" => 'books#search'
  match "books/display" => 'books#show' 
  match "books/test" => "books#test"

  resources :books
  resources :users
  match  "renren/login"=>'Renren#login'

  match "renren/loginnext"=>'renren#loginnext'

  get "renren/message"

  get "main/login"
  
  get "book/add_book_page"
  get "book/ajax_books_hint"
  post "book/ajax_books_hint"

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :attr, :publisher, :title, :doubanlink, :imagelink, :author, :ISBN10, :ISBN13
  has_many :ownerships
  has_many :users, :through => :ownerships

  # TODO: the model should not be the same with the database because of serializtion of some property
  def serialize
    self.attr = ActiveSupport::JSON.encode self.attr 
  end

  def deserialize
    self.attr = ActiveSupport::JSON.decode self.attr 
  end
end


# == Schema Information
#
# Table name: books
#
#  id         :integer         not null, primary key
#  publisher  :string(255)
#  created_at :datetime
#  updated_at :datetime
#  title      :string(255)
#  doubanlink :string(255)
#  imagelink  :string(255)
#  author     :string(255)
#  ISBN10     :string(255)
#  ISBN13     :string(255)
#  attr       :text
#  doubanid   :integer
#

app/controllers/book_controller.rb
class BookController < ApplicationController
  
  require 'net/http'

  def add_book_page
    #View of uploading page
     
  end

  def ajax_books_hint
    #give back the hint for possible books
    q = params["q"]

    #debugger
    @db_json_result = douban_book_search(q)
    #render :text=>"the uploaded string is #{douban_book_search(@q)}"
    @html_list = parse_to_html_list(@db_json_result)
    render :partial => "books_possible_list",:content_type => "text/html"
  end

  def douban_book_search(q)
    db_url = "http://api.douban.com/book/subjects?q=#{q}&start-index=1&max-results=5&alt=json"
    url = URI.parse(URI.encode(db_url))
    res = Net::HTTP.get url
    #debugger
    res
  end

  def local_book_search(q)
    #TODO
  end

  def parse_to_html_list(db_book_json_str)
     list_html=''
     db_book_hash = ActiveSupport::JSON.decode "#{db_book_json_str}"
     db_book_hash['entry'].each{|item|
       list_html<< "<li>#{item['title']['$t']} #{item['author'].to_s}</li>"
     }
     list_html
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  require 'net/http' 

  def parse_doubanid(link)
    link[link[0..-2].rindex("/")+1..-2].to_i
  end

  def douban_book_search(q)
    db_url = "http://api.douban.com/book/subjects?q=#{q}&start-index=1&max-results=5&alt=json"
    url = URI.parse(URI.encode(db_url))
    res = Net::HTTP.get url
    #debugger
    db_book_hash = ActiveSupport::JSON.decode res #{db_book_json_str}
    @booklist = []
    db_book_hash['entry'].each do |item|
      book = create_from_douban item
      @booklist.push book
    end
    @booklist    
  end
<<<<<<< HEAD
  
	def new
=======


  def create_from_douban(item)
    book = Book.new(:title => item['title']['$t'])
    # TODO: combine author together or make it a list
    book.author = item['author'][0]['name']['$t'] if !item['author'].nil? && !item['author'][0]['name'].nil?
    item['link'].each do |l|
      book.doubanlink = l['@href'] if l['@rel'] == 'alternate'
      book.imagelink = l['@href'] if l['@rel'] == 'image'
    end
    book.doubanid = parse_doubanid book.doubanlink
    book.attr = item['db:attribute']
    item['db:attribute'].each do |att|
      book.publisher = att['$t'] if att['@name'] == 'publisher'
      book.ISBN10 = att['$t'] if att['@name'] == 'isbn10'
      book.ISBN13 = att['$t'] if att['@name'] == 'isbn13'
    end
#    logger.debug "ISBN: #{book.ISBN13}"
    book
  end

  def new
>>>>>>> 9d8520a26919d100ddea3e527826d87986038c1d
  end

  def index
  end

  def search
    # search douban 
    # TODO: cache what we have, there are too method. 1. cache query & douban response. 2. search what we have first, namely permanent & partial cache
    douban_book_search params[:q]
  end

  def delete
  end

  def edit
  end

  def show
    doubanid = params[:doubanid]
    @book = Book.find_by_doubanid doubanid
    if @book.nil? then
      db_url = "http://api.douban.com/book/subject/#{doubanid}?alt=json"
      url = URI.parse(URI.encode(db_url))
      res = Net::HTTP.get url
      #debugger
      item = ActiveSupport::JSON.decode res #{db_book_json_str}
      @book = create_from_douban item
      @book.serialize
      logger.debug @book.attr
      @book.save
    end
    @book.deserialize
  end

  def update
  end

  def destroy
  end

  def test
  end
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/book/_books_possible_list.erb
<p>books possible list:</p>
<div class='rec_book_list'>
<%hash = ActiveSupport::JSON.decode(@db_json_result) %>
<%  hash['entry'].each {|item|%>
  
  <%author=Array.new%>
  <%if item['author']!=nil%>  
  <% item['author'].each{|a| author<< a['name']['$t']}%>
  <%end%>

  <%publisher=Array.new%>
  <%if item['db:attribute']!=nil%> 
  <% item['db:attribute'].each {|attr|%>
  <%   if attr['@name']=='publisher' then%>
  <%     publisher<<attr['$t']%>
  <%   end%>
  <% }%>
  <%end%>
  
  <%links = Array.new%>
  <%if item['link']!=nil%>
    <%item['link'].each do|link|%>
      <%if link['@rel']=='image'%>
        <%links<<link['@href']%>
      <%end%>
    <%end%>
  <%end%>
  <%if links[0]!=nil%>
    <% links[0].sub('spic','lpic')%>
  <%end%>

  <div class='book'>
    <%if links[0]!=nil%>
      <%=image_tag links[0].sub('spic','mpic')%>
    <%end%>
    <div class='book_info'><%=item['title']['$t']+" "+author.join(" ")+" "+publisher.join(" ")%></div>
  <%= link_to 'Add',new_book_path%>
  </div>
<% }%>
</div>

app/views/book/add_book_page.erb
<h1>Page to upload book</h1>

<input type='text' id="book" onChange="<%= remote_function(:update=>'booksHintList',:url=>{:controller=>'book',:action=>'ajax_books_hint'},:with => "'q='+document.getElementById('book').value") %>"/>

<div id='booksHintList'>
 It's empty Now.
</div>